# Generated by Django 5.1.4 on 2024-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_image_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
        migrations.AddField(
            model_name="article",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="article_videos/"),
        ),
    ]
