# Generated by Django 5.1.4 on 2024-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_image_article_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/article_images/"
            ),
        ),
    ]
